Handle slashes in names of created functions when creating temporary files
purcell/emacs-reformatter pull request #36
Opened 2022-06-15 19:32 UTC by kenranunderscore

Previously, if the symbol passed to `reformatter-define` contained a slash, then the actual formatting would fail due to `make-temp-file` implicitly trying to create a directory inside `/tmp`. I've worked around this by replacing the `/` with an underscore for temp file creation, and written a test to see if it works correctly (and checked that it failed before).

I haven't really written much Elisp though, so there might be a smarter way to do this. Happy about any feedback :)

2022-06-16 10:28 UTC, purcell requested changes
Makes sense, I didn't think of this edge case, and I also didn't find a built-in function for escaping the filenames like this (well, there's one in `vc-git`). So this generally looks helpful and good but I'd make the change as indicated in the comment above.

2022-06-16 10:28 UTC, purcell commented on reformatter.el
> +(defun reformatter--sanitize-symbol-name (sym)
Thanks! Here I would probably make a `(defun reformatter--make-tempfile (sym) ...)` and just localise the replacement there, then the rest of the code would just change to call that function instead of `make-temp-file`.

2022-06-24 08:26 UTC, kenranunderscore commented
I'm not sure how/if I can mark this as "I've made the changes that have been requested". GitHub doesn't seem to pick it up automatically. (Sorry for the extra ping, and please don't take that as me trying to get you to merge this; I'm really not in a hurry, just wondering!)

2022-06-27 07:51 UTC, purcell commented on reformatter.el
> +         (let ((input-file ,(if input-file
If I write an example reformatter like
```el
(reformatter-define dhall-format
  :program dhall-command
  :args '("format"))
```
then the macro-expanded output contains a hard-coded file path that gets re-used for every formatter run. So yes, the quoting needed to work differently. I've pushed a further commit so you can see.

2022-06-27 08:25 UTC, merged

2022-09-26 08:03 UTC, kenranunderscore commented
Hi Steve, I just saw that I forget adding a closing comment here: I wanted to thank you very much for taking the time to merge this in that state and also answer my question about the quoting!

2022-10-04 08:41 UTC, purcell commented
No worries, thanks for your help!